
version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd dist
      - aws --region us-east-2 s3 sync ./ s3://brocktubre.com-angular-code/ --acl=public-read --delete
      - aws cloudfront create-invalidation --distribution-id EYZAXH6Y01AFW --paths /index.html
artifacts:
  files:
    - dist*/**
  discard-paths: yes